### ISSUE TITLE
Provide a way to see recent changes for items edited in a given batch

### ISSUE THREAD

**Issue by Daniel-Mietchen** [Wikidata/editgroups#10]
Ideally, changes linked to or (and perhaps and) from items in that batch, similar to [Special:RecentChangesLinked](https://www.wikidata.org/w/index.php?hidecategorization=1&target=&limit=500&days=30&enhanced=1&title=Special:RecentChangesLinked&urlversion=2)
Example:
- [from P496](https://www.wikidata.org/w/index.php?hidecategorization=1&target=Property%3AP496&limit=500&days=30&enhanced=1&title=Special:RecentChangesLinked&urlversion=2)
- [to P496](https://www.wikidata.org/w/index.php?hidecategorization=1&target=Property%3AP496&showlinkedto=1&limit=500&days=30&enhanced=1&title=Special:RecentChangesLinked&urlversion=2)

**Comment by wetneb** [comment]
That would require a dedicated index that would be very expensive to maintain, so this is probably not going to happen.

One variant of this would be to expose better which properties were added or deleted in a batch, which would make it possible to see all the batches adding or deleting ORCID ids for instance. This would be similar to the existing tagging features on batches. This is more expensive than the current indexing strategy (which only uses data from EventStream) because it generally requires fetching the diffs of the edits, which we currently don't do. But we could restrict that fetching to only the edits with opaque operations codes (such as wbeditentity), and maybe only sample from these (because we don't expect a given batch to use widely varying properties in edits).

**Comment by wetneb** [comment]
I've implemented something different which hopefully fits your needs! You can now filter by properties added or removed in each batch (not all batches are indexed, this will take some time).
